# Jekyll 3 Github defaults
markdown: kramdown
highlighter: rouge

# Setup
title: "Ecole"
tagline: "Learning Environments"
description: "Extensible Combinatorial Optimization Learning Environments"
url: "https://www.ecole.ai/"
baseurl: "/"

author:
  name: "Chair"
  url: "https://cerc-datascience.polymtl.ca/"

# Custom vars
version: "0.0.0"

github:
  repo: "https://github.com/ds4dm/ecole"
